### ISSUE TITLE
View membership card after refresh

### ISSUE THREAD

**Issue by whoabuddy** [openintents/members#1]
I am able to create my membership card using the Stripe test card, but after refreshing the page or navigating to `Visit your own Club!`, the membership card is no longer displayed.

To view the membership ID again I have to process the Stripe transaction again, which gives me the same card. I think it would make sense to be able to view any membership cards created by the user after the fact. :slightly_smiling_face: 

![members](https://user-images.githubusercontent.com/9038904/81414145-6130ca80-90fb-11ea-8d0c-826bfa843661.gif)

**Comment by friedger** [comment]
Fixed in https://github.com/openintents/members/commit/17d5a6f2ca41b7ee52bd698842c6b546498cf9e4
